language: r

sudo: false

script: make hw2Sol

cache: packages

r_packages:
  - rmarkdown
  - neotoma
  - purrr
  - ggplot2
  - plyr
  - reshape2
  - mgcv
  - Bchron
  - viridis
  - dplyr
  - readr
  - gridExtra

r_github_packages:
  - hadley/devtools@efa894ffa

os:
  - linux
  - osx

r:
  - oldrel
  - release
